// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6JWx3_4VDvrVbk1OGdcfaELiqKjmRWn8',
    appId: '1:510976451401:android:245a7c913d31069606f098',
    messagingSenderId: '510976451401',
    projectId: 'mail-berdikari',
    databaseURL:
        'https://mail-berdikari-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mail-berdikari.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBphmdVcbIBwLdIt6vr6gFA2ybDmE9-4ME',
    appId: '1:510976451401:ios:c9af1d303b96d70506f098',
    messagingSenderId: '510976451401',
    projectId: 'mail-berdikari',
    databaseURL:
        'https://mail-berdikari-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mail-berdikari.firebasestorage.app',
    iosBundleId: 'com.innovast.tam',
  );
}
